name: ci
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet build src/src.csproj

    - name: Install picosat
      run: sudo apt install picosat
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.x"
    - name: Run tests
      run: |
        python3 testall.py
